### PR TITLE
Resolves port open issue when app is killed #183

### LINKED ISSUE #183: [BUG] Port not being free on app kill
**Description**
Run a web server on any port and then press "Ctrl+C".

Then `lsof -i tcp:PORT_NUMBER`, e.g. `lsof -i tcp:5000` for 5000 port.

You will have to manually kill the process.

**Expected Behavior**
This should not happen.

### PR DESCRIPTION
**Pull request by anandtripathi5**
**Description**

This PR fixes #183

### CODE REVIEW

**Comment by anandtripathi5** [comment]
@sansyrox

**Review by sansyrox — APPROVED** [review]
Wow! This looks great! 

Thank you! 😄 🚀

**Comment by anandtripathi5** [comment]
Your welcome, I would like to contribute in my free time to this framework. Looks cool

**Comment by sansyrox** [comment]
Thank you @anandtripathi5 . Let me know if you require any help from me. :D

**Comment by anandtripathi5** [comment]
Cool, will pick some of the issues then. Cheers

**Pull request merged**
