### PR TITLE
Build and publish wheels on GitHub Actions

### PR DESCRIPTION
**Pull request by messense**
You need to setup the `PYPI_PASSWORD` secret, use a [api token](https://pypi.org/help/#apitoken) is recommended.

### CODE REVIEW

**Comment by messense** [comment]
Example run: https://github.com/messense/robyn/actions/runs/967265751

**Review by sansyrox — APPROVED** [review]
@messense , this looks amazing! 😄 

I will create a stable branch off my main. Can you add a condition such that it only triggers when  pushed on `stable`?

**Comment by messense** [comment]
> I will create a stable branch off my main. Can you add a condition such that it only triggers when pushed on `stable`?

Sure. 
But I don't think it's really needed, currently it builds the wheels on push and PR, only publishes them to PyPI on new git tag push.

**Comment by messense** [comment]
@davidhewitt There is a weird GIL related error on Python 3.6, I'm not sure why, it works on Python 3.7 and later.
See https://github.com/messense/robyn/runs/2902786370?check_suite_focus=true

**Comment by sansyrox** [comment]
> But I don't think it's really needed, currently it builds the wheels on push and PR, only publishes them to PyPI on new git tag push.
@messense , it makes sense then. Thank you for the amazing contribution. I will be merging this PR! 🚀

**Comment by sansyrox** [comment]
Hey @messense ,
Thank you for the amazing work. We just released the latest version at : https://pypi.org/project/robyn/0.4.1/

**Comment by davidhewitt** [comment]
> Maybe related to the use of prepare_freethreaded_python? 

Possibly. There was a lot of changes to python initialization in Python 3.7.

We also changed the code a lot for PyO3 0.14, so if it works for "future" versions then I'm not too worried.

**Pull request merged**
