### PR TITLE
New Docs Setup

### LINKED ISSUE #202: [Feature Request] improve docs
**Current Behavior**

Try using this https://squidfunk.github.io/mkdocs-material/
**Desired Behavior**

---
**Screenshots / Mockups**

**Alternatives**

---

### PR DESCRIPTION
**Pull request by aryasoni98**
**Description**

This PR fixes #202

### CODE REVIEW

**Comment by sansyrox** [comment]
@aryasoni98 , how do I run this for preview?

**Comment by aryasoni98** [comment]
> @aryasoni98 , how do I run this for preview?

cd /docs/new-docs/robyn
run ` hugo server `

**Comment by aryasoni98** [comment]
@sansyrox Any review !

**Comment by sansyrox** [comment]
Hi @aryasoni98 ,

Apologies. I am moving houses right now(and hating adulting in parallel). 

I will review this PR by Saturday/Sunday eod.

**Comment by sansyrox** [comment]
@aryasoni98 , I installed `hugo` from `homebrew` and I tried to follow the steps you shared with me.

I am getting this error:

```
Error: Unable to locate config file or config directory. Perhaps you need to create a new site.
```

**Comment by aryasoni98** [comment]
> @aryasoni98 , I installed `hugo` from `homebrew` and I tried to follow the steps you shared with me.
> 
> I am getting this error:
> 
> ```
> Error: Unable to locate config file or config directory. Perhaps you need to create a new site.
> ```

Okay, I will check and update the code shortly .

**Comment by aryasoni98** [comment]
@sansyrox i try to push the ` cd /docs/new-docs/robyn ` folder but i didn’t.

**Comment by sansyrox** [comment]
@aryasoni98 , looks like git is treating `robyn` folder like a submodule.

**Comment by aryasoni98** [comment]
> treating `robyn` folder like a submodule.

@sansyrox Any suggestion how to fix this issue .

**Comment by sansyrox** [comment]
Closing as this a stale PR.

**Pull request closed without merging**
