### PR TITLE
Upgrade GitHub Actions and add Python 3.10

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by sansyrox** [comment]
@cclauss , what is the error that you were getting?

**Comment by cclauss** [comment]
https://github.com/sansyrox/robyn/runs/7300084539?check_suite_focus=true

**Comment by sansyrox** [comment]
@cclauss , I am unable to understand what it means by this statement

>  /home/runner/work/_actions/uraimo/run-on-arch-action/v2.2.0/src/run-on-arch-commands.sh: line 5: python3.10: command not found

Does it mean that we are using the wrong image? Or the image doesn't exist? Or is it not possible to run 3.10 on linux cross? Or something else?

**Comment by cclauss** [comment]
The `build container` step succeeds but the `run container` step fails.  This means that there is no Python 3.10 executable inside the container.  My recommendation is that we land this PR s is because it is a nice improvement.  After this has landed, we can circle back with another PR that ensures that Py310 is in the containers.

**Comment by sansyrox** [comment]
@cclauss , thank you! :D This looks good at first glance. I am at a conference currently, I will have a proper look by Thursday eod.

**Comment by cclauss** [comment]
Thanks.  No rush.

**Review by sansyrox — APPROVED** [review]
LGTM! :rocket:

**Pull request merged**
