### PR TITLE
Try fixing windows pipeline

### PR DESCRIPTION
**Pull request by sansyrox**
**Description**

This PR fixes #

### CODE REVIEW

**Comment by sansyrox** [comment]
Hi @messense ,

I hope you are doing well. Do you happen to know why the windows builds are failing for `maturin-action`?

**Comment by messense** [comment]
I think it's fixed in https://github.com/PyO3/maturin/pull/923, I'm [releasing a new beta version](https://github.com/PyO3/maturin/actions/runs/2344052758) please give it a try once it lands. If it fixes the issue, I'll release a new version soon.

```yaml
  uses: https://github.com/messense/maturin-action/tree/v1v1
  with:
    maturin-version: v0.12.17-beta.1
```

**Comment by sansyrox** [comment]
Thank you so much @messense . I will give it a go :D

**Comment by sansyrox** [comment]
@messense , I did give it a go but the configuration above is shown as invalid in github actions.

**Comment by sansyrox** [comment]
Hi @messense ,

I just tried the latest release. It works now! Thank you so much! 😄 ❇️

**Pull request closed without merging**
