### PR TITLE
Don't run sync functions in pool

### PR DESCRIPTION
**Pull request by JackThomson2**
Don't run synchronous functions in the tokio threadpool, this is just adding overhead. We need to acquire the GIL anyway so it won't be run async anyway. Server will still accept connections as this is done in a worker thanks to Actix design

This PR fixes #

### CODE REVIEW

**Comment by sansyrox** [comment]
@JackThomson2 , I just had a look at the PR. It looks good.

But I have one question. Does it have any effect on the performance?

**Comment by JackThomson2** [comment]
Yeah it is much faster than previously, I'll make another PR to remove async from the function in techempowered as well should help scores go up massively

**Comment by sansyrox** [comment]
@JackThomson2 , that sounds great. Thank you! :D

I am not sure how Techempowered benchmarks are scored. But if it is not a dynamic request, do  you think const requests would help: https://sansyrox.github.io/robyn/#/features?id=const-requests ?

**Review by sansyrox — APPROVED** [review]
LGTM! :sparkles:

**Pull request merged**
